### ISSUE TITLE
Morning session peer to peer code review

### ISSUE THREAD

**Issue by Besufekad-HAZ** [jeanbuhendwa/awesome-books#2]
- Add a required attribute in books and Author input field
 https://github.com/jeanbuhendwa/awesome-books/blob/350b4cd799fe090dd61a1f546f2a9b087b0f8db2/index.html#L20-L22
- Add a placeholder in books and author input field
 https://github.com/jeanbuhendwa/awesome-books/blob/350b4cd799fe090dd61a1f546f2a9b087b0f8db2/index.html#L20-L22
- Although the current ID generator works fine as an optional way you can try to generate a unique ID for each book added (you can use Math. random, round, or other possible functions)
 https://github.com/jeanbuhendwa/awesome-books/blob/350b4cd799fe090dd61a1f546f2a9b087b0f8db2/scripts.js#L54

**Comment by jeanbuhendwa** [comment]
Thanks for the review.
